esphome:
  name: "dev"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API

# api:
#  encryption:
#    key: "A5+uM9ViwHaWIQN856L9wg+W5Ik9HHjukSPw4IMWshA="

ota:
  password: "e8e8649a57fb76beef4f651dafe5c6d1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Home Fallback Hotspot"
    password: "zX5OUxenQCUs"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: esphome/dev
  reboot_timeout: 60s
  keepalive: 60s
  on_connect:
    then:
      - logger.log: "MQTT: Connected"
  on_disconnect:       
    then:
      - logger.log: "MQTT: Disconnected"
#   on_message:
#     - topic: "dev/led/status/on"
#       qos: 0
#       then:
#         - logger.log: "MQTT: dev/led/status ON"
#         - switch.turn_on: led_status
#     - topic: "dev/led/status/off"
#       qos: 0
#       then:
#         - logger.log: "MQTT: dev/led/status OFF"
#         - switch.turn_off: led_status
      
switch:
  - id: led_red
    platform: gpio
    name: "Red LED"
    pin: 21
  - id: led_green
    platform: gpio
    name: "Green LED"
    pin: 22
  - id: led_blue
    platform: gpio
    name: "Blue LED"
    pin: 23
  - id: led_status
    platform: gpio
    name: "Status LED"
    pin: 15
    
binary_sensor:
  - id: button_push
    name: "On-Board Button"
    platform: gpio
    pin: 
      number: 13
      mode: 
        input: true
        pulldown: true
    filters:
      - delayed_off: 10ms
      
output:
  - id: led_rgb_blue 
    platform: ledc
    pin: GPIO5
    max_power: 50%
    inverted: true
  
  - id: led_rgb_green
    platform: ledc
    pin: GPIO18
    max_power: 50%
    inverted: true
    
  - id: led_rgb_red
    platform: ledc
    pin: GPIO19
    max_power: 50%
    inverted: true
    
light:
  - platform: rgb
    name: "RGB Led"
    red: led_rgb_red
    green: led_rgb_green
    blue: led_rgb_blue
